### ISSUE TITLE
[HashFiles] Support folders

### ISSUE THREAD

**Issue by DJiMMYSVRT** [Otiel/xyplorer-scripts#1]
Is it possible to make this script hash files inside selected  folders or subfolders?

Would be glad if u could help!!!
Thanks in advance!!!

**Comment by Otiel** [comment]
Sure, check the latest version:
https://github.com/Otiel/xyplorer-scripts/blob/master/Scripts/HashFiles.xys

It will hash files contained in the selected folders (recursively).
